theme = "github_dark"

[editor]
line-number = "absolute"
mouse = false
idle-timeout = 100
completion-timeout = 50
cursorline = true
rulers = [120]
popup-border = "all"

[editor.inline-diagnostics]
cursor-line = "hint"
# other-lines = "error"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.file-picker]
hidden = false

[keys.normal]
# Muscle memory from VIM
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable

[keys.normal.space]
o = ":sh tmux popup -d $(PWD)"
f = ":sh tmux display-popup -E yazi $(PWD)"
v = ["vsplit_new", "file_picker_in_current_directory"]
h = ["hsplit_new", "file_picker_in_current_directory"]
"space" = "file_picker_in_current_directory"

[keys.normal.space.t]
# Open test file (test_file_lookup only works for elixir right now)
t = ":open %sh{~/.bin/helix/test_file_lookup $(realpath %{buffer_name})}"
# Run the full mix test suite
a = [":sh mix test 2>&1 | tee /tmp/helix_output.log | tail -n 19"]
# Run the mix test suite for the current file
r = [":sh mix test %{buffer_name} 2>&1 | tee /tmp/helix_output.log | tail -n 19"]
# Run the test suite for the current file & line
l = [":sh mix test %{buffer_name}:%{cursor_line}"]
# Open the output of the last ran test suite
o = [":open /tmp/helix_output.log"]


[keys.normal.space.i]
# Show blame info for current line
b = ":sh git -C $(dirname $(realpath %{buffer_name})) blame -L %{cursor_line},%{cursor_line} $(realpath %{buffer_name})"

 
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
end = "no_op"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]

[keys.select]
# Muscle memory from VIM
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
S = "surround_add" # Basically 99% of what I use vim-surround for
"!" = ["split_selection_on_newline", "extend_to_line_bounds", ":sort"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"
